<?php

namespace Sprint\Migration;


class Version20221019160527 extends Version
{
    protected $description = "Разделы каталога";

    protected $moduleVersion = "3.22.2";

    /**
     * @throws Exceptions\HelperException
     * @return bool|void
     */
    public function up()
    {
        $helper = $this->getHelperManager();

        $iblockId = $helper->Iblock()->getIblockIdIfExists(
            'aspro_max_catalog',
            'aspro_max_catalog'
        );

        $helper->Iblock()->addSectionsFromTree(
            $iblockId,
            array (
  0 => 
  array (
    'NAME' => 'Мебель для школ и других помещений',
    'CODE' => 'mebel_dlya_shkol_i_drugikh_pomeshcheniy',
    'SORT' => '500',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'DESCRIPTION' => NULL,
    'DESCRIPTION_TYPE' => 'text',
    'UF_SECTION_DESCR' => NULL,
    'UF_SECTION_TEMPLATE' => NULL,
    'UF_POPULAR' => NULL,
    'UF_CATALOG_ICON' => NULL,
    'UF_OFFERS_TYPE' => NULL,
    'UF_TABLE_SIZES' => NULL,
    'UF_ELEMENT_DETAIL' => NULL,
    'UF_SECTION_BG_IMG' => NULL,
    'UF_SECTION_BG_DARK' => NULL,
    'UF_SECTION_TIZERS' => false,
    'UF_HELP_TEXT' => NULL,
    'UF_MENU_BANNER' => NULL,
    'UF_REGION' => NULL,
    'UF_PICTURE_RATIO' => NULL,
    'UF_LINE_ELEMENT_CNT' => NULL,
    'UF_MENU_BRANDS' => false,
    'UF_LINKED_BANNERS' => false,
    'UF_BANNERS_BOTTOM' => NULL,
    'UF_BANNERS_WIDE' => NULL,
    'UF_BANNERS_MOBILE' => NULL,
    'UF_LINKED_BLOG' => false,
    'UF_BLOG_BOTTOM' => NULL,
    'UF_BLOG_WIDE' => NULL,
    'UF_BLOG_MOBILE' => NULL,
    'CHILDS' => 
    array (
      0 => 
      array (
        'NAME' => 'Диваны',
        'CODE' => 'divany',
        'SORT' => '120',
        'ACTIVE' => 'Y',
        'XML_ID' => '544',
        'DESCRIPTION' => '<p>Выбирайте диван по габаритам, типу трансформации и количеству посадочных мест. Отмечайте в фильтре нужные характеристики, изучайте описание и сравнивайте товары. Добавляйте в корзину и оформляйте покупку в 1 клик. Возникли вопросы при выборе материала обивки дивана или по цветовой гамме интерьера? К вашим услугам онлайн-консультанты.</p>
<p>
Наша компания является производителем, и часть ассортимента регулярно обновляется. Наблюдайте за обновлениями товара на сайте и успейте воспользоваться заманчивыми предложениями со скидками!</p>
',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'Покупка мягкой мебели по окончании ремонта или для обновления интерьера — отличный повод заглянуть в интернет-магазин. В каталоге вы найдете диваны пантографы, еврокнижки, клик-кляк, книжки, угловые и другие. ',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4253',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
          0 => 3669,
          1 => 3668,
          2 => 3667,
          3 => 3670,
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '117',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      1 => 
      array (
        'NAME' => 'Шкафы',
        'CODE' => 'shkafy',
        'SORT' => '490',
        'ACTIVE' => 'Y',
        'XML_ID' => '550',
        'DESCRIPTION' => '<p>Покупка крупногабаритной мебели — волнительный процесс. Не переживайте: в каталоге представлено 150 моделей и 12 видов шкафов. Только ведущие производители и стильная мебель.
</p>
<p>
Наша компания является производителем, и часть ассортимента регулярно обновляется. Наблюдайте за обновлениями товара на сайте и успейте воспользоваться заманчивыми предложениями со скидками!
</p>',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'Выбирайте шкафы по типу конструкции, способу комплектации, форме, стилю или габаритам. На сайте встретите разнообразие моделей, цветовой гаммы и точно сделаете правильный выбор. В интернет-магазине возможно оформление доставки, консультация менеджеров, выбор услуг по сборке или ремонту мебели.',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4254',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '118',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      2 => 
      array (
        'NAME' => 'Столы',
        'CODE' => 'stoly',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => '553',
        'DESCRIPTION' => '<p>В ассортименте есть нескладные и складные виды столов, 21 вариант цвета, 4 материала столешниц, различные габариты и формы. Укомплектуйте столы подходящими по стилю стульями и табуретами. Меняйте интерьер до неузнаваемости с нашим интернет-магазином!</p>
<p>
Чтобы не растеряться в таком разнообразии, онлайн-консультанты помогут с выбором. Действует доставка по городу. Наблюдайте за обновлениями товара на сайте и успейте воспользоваться заманчивыми предложениями со скидками!</p>
',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'Наш интернет-каталог представляет 240 моделей столов. Здесь найдете компьютерные, кухонные, обеденные, офисные и письменные столы с ценами от 2 000 р. Воспользуйтесь удобным фильтром в каталоге и выберите стол своей мечты!',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4255',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '0',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      3 => 
      array (
        'NAME' => 'Стулья',
        'CODE' => 'stulya',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => '371',
        'DESCRIPTION' => '<p>Мы производим продукцию только из высококачественных и экологически чистых материалов. Мебель прослужит долгое время и станет незаменимым атрибутом в обстановке дома.</p>
<p>
Придайте своему интерьеру благородный вид. Подбирайте мебель с помощью фильтра по материалу, габаритам и стилю. Наши онлайн-консультанты помогут подобрать стулья под ваши запросы и ответят на возникшие вопросы по ассортименту. Будем рады вам помочь с выбором!
</p>',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'Готовы создать уют в своем доме и добавить «изюминку» в дизайн? Наш интернет-магазин поможет подобрать стулья в гостиную, офис или на кухню. Разнообразие материалов, форм и расцветок позволит легко подобрать к столам и интерьеру нужные стулья и табуреты.',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4257',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '0',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      4 => 
      array (
        'NAME' => 'Вешалки',
        'CODE' => 'veshalki',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      5 => 
      array (
        'NAME' => 'Комплектующие',
        'CODE' => 'komplektuyushchie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      6 => 
      array (
        'NAME' => 'Трибуны',
        'CODE' => 'tribuny',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      7 => 
      array (
        'NAME' => 'Фонтанчик',
        'CODE' => 'fontanchik',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      8 => 
      array (
        'NAME' => 'Мягкие модули',
        'CODE' => 'myagkie_moduli',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
    ),
  ),
  1 => 
  array (
    'NAME' => 'Товары и оборудование для школ',
    'CODE' => 'tovary_i_oborudovanie_dlya_shkol',
    'SORT' => '500',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'DESCRIPTION' => NULL,
    'DESCRIPTION_TYPE' => 'text',
    'UF_SECTION_DESCR' => NULL,
    'UF_SECTION_TEMPLATE' => NULL,
    'UF_POPULAR' => NULL,
    'UF_CATALOG_ICON' => NULL,
    'UF_OFFERS_TYPE' => NULL,
    'UF_TABLE_SIZES' => NULL,
    'UF_ELEMENT_DETAIL' => NULL,
    'UF_SECTION_BG_IMG' => NULL,
    'UF_SECTION_BG_DARK' => NULL,
    'UF_SECTION_TIZERS' => false,
    'UF_HELP_TEXT' => NULL,
    'UF_MENU_BANNER' => NULL,
    'UF_REGION' => NULL,
    'UF_PICTURE_RATIO' => NULL,
    'UF_LINE_ELEMENT_CNT' => NULL,
    'UF_MENU_BRANDS' => false,
    'UF_LINKED_BANNERS' => false,
    'UF_BANNERS_BOTTOM' => NULL,
    'UF_BANNERS_WIDE' => NULL,
    'UF_BANNERS_MOBILE' => NULL,
    'UF_LINKED_BLOG' => false,
    'UF_BLOG_BOTTOM' => NULL,
    'UF_BLOG_WIDE' => NULL,
    'UF_BLOG_MOBILE' => NULL,
    'CHILDS' => 
    array (
      0 => 
      array (
        'NAME' => 'Витрины для школы',
        'CODE' => 'vitriny_dlya_shkoly',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      1 => 
      array (
        'NAME' => 'Парты и стулья школьные',
        'CODE' => 'party_i_stulya_shkolnye',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Точка роста',
            'CODE' => 'tochka_rosta',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
        ),
      ),
      2 => 
      array (
        'NAME' => 'Маркерные и меловые доски',
        'CODE' => 'markernye_i_melovye_doski',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      3 => 
      array (
        'NAME' => 'Интерактивное оборудование для школ',
        'CODE' => 'interaktivnoe_oborudovanie_dlya_shkol',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Интерактивные 3D Пирамиды',
            'CODE' => 'interaktivnye_3d_piramidy',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          1 => 
          array (
            'NAME' => 'VR-оборудование',
            'CODE' => 'vr_oborudovanie',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          2 => 
          array (
            'NAME' => 'Интерактивные доски и комплексы',
            'CODE' => 'interaktivnye_doski_i_kompleksy',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          3 => 
          array (
            'NAME' => 'Интерактивные панели и планшеты',
            'CODE' => 'interaktivnye_paneli_i_planshety',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          4 => 
          array (
            'NAME' => 'Интерактивные песочницы',
            'CODE' => 'interaktivnye_pesochnitsy',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          5 => 
          array (
            'NAME' => 'Интерактивные столы и киоски',
            'CODE' => 'interaktivnye_stoly_i_kioski',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          6 => 
          array (
            'NAME' => 'Интерактивные трибуны',
            'CODE' => 'interaktivnye_tribuny',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          7 => 
          array (
            'NAME' => 'Полы и стены',
            'CODE' => 'poly_i_steny',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          8 => 
          array (
            'NAME' => 'Интерактивный скалодром',
            'CODE' => 'interaktivnyy_skalodrom',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          9 => 
          array (
            'NAME' => 'Квадрокоптеры',
            'CODE' => 'kvadrokoptery',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
        ),
      ),
      4 => 
      array (
        'NAME' => 'Документ-камеры',
        'CODE' => 'dokument_kamery',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      5 => 
      array (
        'NAME' => 'Плакатницы и экспозиционные стенды',
        'CODE' => 'plakatnitsy_i_ekspozitsionnye_stendy',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      6 => 
      array (
        'NAME' => 'Стенды в школу',
        'CODE' => 'stendy_v_shkolu',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      7 => 
      array (
        'NAME' => 'Оборудование для музея',
        'CODE' => 'oborudovanie_dlya_muzeya',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      8 => 
      array (
        'NAME' => 'Световое оборудование',
        'CODE' => 'svetovoe_oborudovanie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      9 => 
      array (
        'NAME' => 'Lego',
        'CODE' => 'lego',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      10 => 
      array (
        'NAME' => 'Пожарное оборудование',
        'CODE' => 'pozharnoe_oborudovanie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      11 => 
      array (
        'NAME' => 'Инклюзивное оборудование',
        'CODE' => 'inklyuzivnoe_oborudovanie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      12 => 
      array (
        'NAME' => 'Оборудование для ПДД',
        'CODE' => 'oborudovanie_dlya_pdd',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      13 => 
      array (
        'NAME' => 'Оборудование для бассейна',
        'CODE' => 'oborudovanie_dlya_basseyna',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      14 => 
      array (
        'NAME' => 'Робототехника',
        'CODE' => 'robototekhnika',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      15 => 
      array (
        'NAME' => 'Санитарно-техническое оборудование',
        'CODE' => 'sanitarno_tekhnicheskoe_oborudovanie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      16 => 
      array (
        'NAME' => 'Цифровое лабораторное оборудование',
        'CODE' => 'tsifrovoe_laboratornoe_oborudovanie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      17 => 
      array (
        'NAME' => 'Техника для климата',
        'CODE' => 'tekhnika_dlya_klimata',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      18 => 
      array (
        'NAME' => 'Уличное оборудование',
        'CODE' => 'ulichnoe_oborudovanie',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Спортивное оборудование',
            'CODE' => 'sportivnoe_oborudovanie',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => '0',
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => '0',
            'UF_SECTION_TIZERS' => 
            array (
            ),
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => 
            array (
            ),
            'UF_LINKED_BANNERS' => 
            array (
            ),
            'UF_BANNERS_BOTTOM' => '0',
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => 
            array (
            ),
            'UF_BLOG_BOTTOM' => '0',
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
          1 => 
          array (
            'NAME' => 'Благоустройство',
            'CODE' => 'blagoustroystvo',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => '',
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => '0',
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => '0',
            'UF_SECTION_TIZERS' => 
            array (
            ),
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => 
            array (
            ),
            'UF_LINKED_BANNERS' => 
            array (
            ),
            'UF_BANNERS_BOTTOM' => '0',
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => 
            array (
            ),
            'UF_BLOG_BOTTOM' => '0',
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
        ),
      ),
      19 => 
      array (
        'NAME' => 'Оргтехника',
        'CODE' => 'orgtekhnika',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      20 => 
      array (
        'NAME' => 'Хозтовары',
        'CODE' => 'khoztovary',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
    ),
  ),
  2 => 
  array (
    'NAME' => 'Оформление кабинетов и других помещений',
    'CODE' => 'oformlenie_kabinetov_i_drugikh_pomeshcheniy',
    'SORT' => '500',
    'ACTIVE' => 'Y',
    'XML_ID' => NULL,
    'DESCRIPTION' => NULL,
    'DESCRIPTION_TYPE' => 'text',
    'UF_SECTION_DESCR' => NULL,
    'UF_SECTION_TEMPLATE' => NULL,
    'UF_POPULAR' => NULL,
    'UF_CATALOG_ICON' => NULL,
    'UF_OFFERS_TYPE' => NULL,
    'UF_TABLE_SIZES' => NULL,
    'UF_ELEMENT_DETAIL' => NULL,
    'UF_SECTION_BG_IMG' => NULL,
    'UF_SECTION_BG_DARK' => NULL,
    'UF_SECTION_TIZERS' => false,
    'UF_HELP_TEXT' => NULL,
    'UF_MENU_BANNER' => NULL,
    'UF_REGION' => NULL,
    'UF_PICTURE_RATIO' => NULL,
    'UF_LINE_ELEMENT_CNT' => NULL,
    'UF_MENU_BRANDS' => false,
    'UF_LINKED_BANNERS' => false,
    'UF_BANNERS_BOTTOM' => NULL,
    'UF_BANNERS_WIDE' => NULL,
    'UF_BANNERS_MOBILE' => NULL,
    'UF_LINKED_BLOG' => false,
    'UF_BLOG_BOTTOM' => NULL,
    'UF_BLOG_WIDE' => NULL,
    'UF_BLOG_MOBILE' => NULL,
    'CHILDS' => 
    array (
      0 => 
      array (
        'NAME' => 'Библиотека',
        'CODE' => 'biblioteka',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
        'CHILDS' => 
        array (
          0 => 
          array (
            'NAME' => 'Мебель для документов',
            'CODE' => 'mebel_dlya_dokumentov',
            'SORT' => '500',
            'ACTIVE' => 'Y',
            'XML_ID' => NULL,
            'DESCRIPTION' => NULL,
            'DESCRIPTION_TYPE' => 'text',
            'UF_SECTION_DESCR' => NULL,
            'UF_SECTION_TEMPLATE' => NULL,
            'UF_POPULAR' => NULL,
            'UF_CATALOG_ICON' => NULL,
            'UF_OFFERS_TYPE' => NULL,
            'UF_TABLE_SIZES' => NULL,
            'UF_ELEMENT_DETAIL' => NULL,
            'UF_SECTION_BG_IMG' => NULL,
            'UF_SECTION_BG_DARK' => NULL,
            'UF_SECTION_TIZERS' => false,
            'UF_HELP_TEXT' => NULL,
            'UF_MENU_BANNER' => NULL,
            'UF_REGION' => NULL,
            'UF_PICTURE_RATIO' => NULL,
            'UF_LINE_ELEMENT_CNT' => NULL,
            'UF_MENU_BRANDS' => false,
            'UF_LINKED_BANNERS' => false,
            'UF_BANNERS_BOTTOM' => NULL,
            'UF_BANNERS_WIDE' => NULL,
            'UF_BANNERS_MOBILE' => NULL,
            'UF_LINKED_BLOG' => false,
            'UF_BLOG_BOTTOM' => NULL,
            'UF_BLOG_WIDE' => NULL,
            'UF_BLOG_MOBILE' => NULL,
          ),
        ),
      ),
      1 => 
      array (
        'NAME' => 'Кабинет Химии',
        'CODE' => 'kabinet_khimii',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      2 => 
      array (
        'NAME' => 'Кабинет Физики',
        'CODE' => 'kabinet_fiziki',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      3 => 
      array (
        'NAME' => 'Гардероб',
        'CODE' => 'garderob',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      4 => 
      array (
        'NAME' => 'Столовая и пищеблок в школе',
        'CODE' => 'stolovaya_i_pishcheblok_v_shkole',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      5 => 
      array (
        'NAME' => 'Кабинет ИЗО, МХК, Черчения',
        'CODE' => 'kabinet_izo_mkhk_chercheniya',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => NULL,
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => NULL,
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => NULL,
        'UF_SECTION_TIZERS' => false,
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      6 => 
      array (
        'NAME' => 'Входная зона и холл',
        'CODE' => 'vkhodnaya_zona_i_kholl',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      7 => 
      array (
        'NAME' => 'Функциональный актовый зал',
        'CODE' => 'funktsionalnyy_aktovyy_zal',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      8 => 
      array (
        'NAME' => 'Спортивный комплекс в школе',
        'CODE' => 'sportivnyy_kompleks_v_shkole',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      9 => 
      array (
        'NAME' => 'Зона отдыха',
        'CODE' => 'zona_otdykha',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      10 => 
      array (
        'NAME' => 'Медицинский кабинет',
        'CODE' => 'meditsinskiy_kabinet',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      11 => 
      array (
        'NAME' => 'Кабинет психолога',
        'CODE' => 'kabinet_psikhologa',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      12 => 
      array (
        'NAME' => 'Уголок природы для школы',
        'CODE' => 'ugolok_prirody_dlya_shkoly',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      13 => 
      array (
        'NAME' => 'Кабинет Профильные классы школы',
        'CODE' => 'kabinet_profilnye_klassy_shkoly',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      14 => 
      array (
        'NAME' => 'Кабинет Учительская',
        'CODE' => 'kabinet_uchitelskaya',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      15 => 
      array (
        'NAME' => 'Кабинет Руководителя и Администрации',
        'CODE' => 'kabinet_rukovoditelya_i_administratsii',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      16 => 
      array (
        'NAME' => 'Кабинет начальной школы',
        'CODE' => 'kabinet_nachalnoy_shkoly',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      17 => 
      array (
        'NAME' => 'Кабинет Биологии',
        'CODE' => 'kabinet_biologii',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      18 => 
      array (
        'NAME' => 'Кабинет Астрономии',
        'CODE' => 'kabinet_astronomii',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      19 => 
      array (
        'NAME' => 'Кабинет Географии',
        'CODE' => 'kabinet_geografii',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      20 => 
      array (
        'NAME' => 'Кабинет Русского языка и литературы',
        'CODE' => 'kabinet_russkogo_yazyka_i_literatury',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      21 => 
      array (
        'NAME' => 'Кабинет Математики',
        'CODE' => 'kabinet_matematiki',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      22 => 
      array (
        'NAME' => 'Кабинет Истории и обществознания',
        'CODE' => 'kabinet_istorii_i_obshchestvoznaniya',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      23 => 
      array (
        'NAME' => 'Кабинет Иностранного языка',
        'CODE' => 'kabinet_inostrannogo_yazyka',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      24 => 
      array (
        'NAME' => 'Кабинет ОБЖ и НВП',
        'CODE' => 'kabinet_obzh_i_nvp',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      25 => 
      array (
        'NAME' => 'Кабинет Технологии',
        'CODE' => 'kabinet_tekhnologii',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      26 => 
      array (
        'NAME' => 'Кабинет Музыки',
        'CODE' => 'kabinet_muzyki',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      27 => 
      array (
        'NAME' => 'Кабинет Информатики',
        'CODE' => 'kabinet_informatiki',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => NULL,
        'DESCRIPTION' => '',
        'DESCRIPTION_TYPE' => 'text',
        'UF_SECTION_DESCR' => NULL,
        'UF_SECTION_TEMPLATE' => NULL,
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => NULL,
        'UF_OFFERS_TYPE' => NULL,
        'UF_TABLE_SIZES' => NULL,
        'UF_ELEMENT_DETAIL' => NULL,
        'UF_SECTION_BG_IMG' => NULL,
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => NULL,
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => 
        array (
        ),
        'UF_LINKED_BANNERS' => 
        array (
        ),
        'UF_BANNERS_BOTTOM' => '0',
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => 
        array (
        ),
        'UF_BLOG_BOTTOM' => '0',
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
    ),
  ),
  3 => 
  array (
    'NAME' => 'Освещение',
    'CODE' => 'osveshchenie',
    'SORT' => '900',
    'ACTIVE' => 'Y',
    'XML_ID' => '564',
    'DESCRIPTION' => '<p>В нашем интернет-магазине представлено более 50 000 товаров: люстры, светильники, фонари. Мы сотрудничаем только с проверенными брендами и гарантируем высокое качество изделий.</p>
<p>
 У нас вы найдете все необходимое для освещения квартир, загородных домов и участков, а также офисных помещений. Создайте комфорт для глаз вместе с нашим интернет-магазином. Приобрести товары вы можете в 1 клик. Подробнее о продукции вы можете узнать через онлайн-чат или у консультантов в торговом зале.</p>
<p>
Сделайте вашу жизнь светлее! Подробнее об условиях доставки читайте в разделе «Как купить».</p>',
    'DESCRIPTION_TYPE' => 'html',
    'UF_SECTION_DESCR' => 'Комфорт и уют в доме строятся из мелочей. И освещение здесь играет немаловажную роль. Правильный свет поможет сделать помещение ярче, визуально больше и интереснее. Выбирайте подходящие модели в зависимости от назначения комнаты.',
    'UF_SECTION_TEMPLATE' => '104',
    'UF_POPULAR' => '1',
    'UF_CATALOG_ICON' => '4303',
    'UF_OFFERS_TYPE' => '0',
    'UF_TABLE_SIZES' => '0',
    'UF_ELEMENT_DETAIL' => '0',
    'UF_SECTION_BG_IMG' => '0',
    'UF_SECTION_BG_DARK' => '0',
    'UF_SECTION_TIZERS' => 
    array (
    ),
    'UF_HELP_TEXT' => NULL,
    'UF_MENU_BANNER' => NULL,
    'UF_REGION' => NULL,
    'UF_PICTURE_RATIO' => NULL,
    'UF_LINE_ELEMENT_CNT' => NULL,
    'UF_MENU_BRANDS' => false,
    'UF_LINKED_BANNERS' => false,
    'UF_BANNERS_BOTTOM' => NULL,
    'UF_BANNERS_WIDE' => NULL,
    'UF_BANNERS_MOBILE' => NULL,
    'UF_LINKED_BLOG' => false,
    'UF_BLOG_BOTTOM' => NULL,
    'UF_BLOG_WIDE' => NULL,
    'UF_BLOG_MOBILE' => NULL,
    'CHILDS' => 
    array (
      0 => 
      array (
        'NAME' => 'Люстры',
        'CODE' => 'lyustry',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => '574',
        'DESCRIPTION' => '<p>
	 В нашем интернет-магазине представлен широкий выбор ассортимента на любой вкус:
</p>
<ul>
	<li>
		 каскадные;
 </li>
	<li>
		 потолочные;
 </li>
	<li>
		 подвесные;
 </li>
	<li>
		 светодиодные;
 </li>
	<li>
		 с пультом управления и другие.
 </li>
</ul>
<p>
	 При выборе подходящей модели нужно ориентироваться на высоту и размер потолка. А также определиться с запросами относительно режимов включения, мощности освещения и особенностей патронов. Если вы затрудняетесь с поиском люстры, мы поможем вам и найдем максимально подходящий вариант. Просто напишите в онлайн-чат на сайте или обратитесь к консультантам в торговом зале.
</p>
<p>
	 Покупайте люстры в нашем магазине и создавайте вокруг себя уют!
</p>',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'Ни одно помещение не обходится без люстры. Она не только необходима для создания освещения, но и является весомой деталью в интерьере любой комнаты. Мы работаем только с проверенными производителями и гарантируем качество изделий. Всего насчитывается более 12 000 видов изделий 16 брендов. ',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4305',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '117',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      1 => 
      array (
        'NAME' => 'Светильники',
        'CODE' => 'svetilniki',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => '575',
        'DESCRIPTION' => '<p>
	 Жизнь становится светлее и ярче с правильным светильником. В нашем магазине представлено более 16 000 моделей на любой вкус и бюджет:
</p>
<ul>
	<li>
		 потолочные;
 </li>
	<li>
		 подвесные;
 </li>
	<li>
		 настенные;
 </li>
	<li>
		 накладные;
 </li>
	<li>
		 светодиодные.
 </li>
</ul>
<p>
	 Если затрудняетесь в поиске подходящего светильника, обратитесь к менеджерам в торговом зале или просто напишите в онлайн-чат на сайте. Подберем идеальный вариант.
</p>',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'При выборе светильника нужно определиться, для какой цели он будет использоваться. Если он необходим для дополнения дизайнерской задумки, то здесь важны габариты, цветовая гамма и форма. Но если изделие нужно только для хорошего освещения, то стоит ориентироваться на количество, тип и мощность ламп.',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4307',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '0',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
      2 => 
      array (
        'NAME' => 'Фонари',
        'CODE' => 'fonari',
        'SORT' => '500',
        'ACTIVE' => 'Y',
        'XML_ID' => '576',
        'DESCRIPTION' => '<p>
	 В нашем интернет-магазине представлен широкий выбор фонарей как для спорта, туризма, так и для оформления уличной зоны вашего участка.
</p>
<p>
	 У нас вы можете найти следующие виды товаров:
</p>
<ul>
<li>подвесные;</li>
<li>кемпинговые;</li>
<li>наземные уличные;</li>
<li>настенные уличные.</li>
</ul>
<p>
	 Покупайте фонари в нашем интернет-магазине по выгодным ценам всего в 1 клик. Будьте всегда на светлой стороне!
</p>',
        'DESCRIPTION_TYPE' => 'html',
        'UF_SECTION_DESCR' => 'Чтобы подобрать идеальный вариант для покупки, нужно учесть необходимые мощность, дальность освещения, механизм работы, габариты и дизайн. Если не знаете, какой товар лучше приобрести, проконсультируйтесь у наших менеджеров через онлайн-чат. Поможем со всем разобраться.',
        'UF_SECTION_TEMPLATE' => '104',
        'UF_POPULAR' => '0',
        'UF_CATALOG_ICON' => '4309',
        'UF_OFFERS_TYPE' => '0',
        'UF_TABLE_SIZES' => '0',
        'UF_ELEMENT_DETAIL' => '0',
        'UF_SECTION_BG_IMG' => '0',
        'UF_SECTION_BG_DARK' => '0',
        'UF_SECTION_TIZERS' => 
        array (
        ),
        'UF_HELP_TEXT' => NULL,
        'UF_MENU_BANNER' => NULL,
        'UF_REGION' => NULL,
        'UF_PICTURE_RATIO' => '0',
        'UF_LINE_ELEMENT_CNT' => NULL,
        'UF_MENU_BRANDS' => false,
        'UF_LINKED_BANNERS' => false,
        'UF_BANNERS_BOTTOM' => NULL,
        'UF_BANNERS_WIDE' => NULL,
        'UF_BANNERS_MOBILE' => NULL,
        'UF_LINKED_BLOG' => false,
        'UF_BLOG_BOTTOM' => NULL,
        'UF_BLOG_WIDE' => NULL,
        'UF_BLOG_MOBILE' => NULL,
      ),
    ),
  ),
)        );
    }

    public function down()
    {
        //your code ...
    }
}
